# workflows/client-applications-check-pr.yml
#
# Client Applications: Check PR
# Checks a client-applications PR for linting and building success.

name: "Client Applications: Check PR"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
        paths:
            - "client-applications/**"
            - "!client-applications/README.md"
            - ".github/workflows/client-applications-check-pr.yml"
            - "core-ts/**"
            - "!core-ts/README.md"
            - ".github/workflows/core-ts-check-pr.yml"
    workflow_dispatch:

jobs:
    # Linting
    # Checks for formatting using ESlint.
    client-applications-check-pr-linting:
        name: Linting
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 14
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14

            - name: Run yarn -i in /desktop
              working-directory: client-applications/desktop
              run: yarn -i

            - name: Check if Code Follows ESLint Standards
              working-directory: client-applications/desktop
              run: yarn lint-check

    # Testing
    # Runs the Client Application test suite.
    client-application-integration-tests:
        name: Integration Testing
        # As of 2021-05-04, tests hang forever when run on Ubuntu. This is fine since tests should ideally
        # be run on our supported environments, which are macOS and Windows.
        #
        # Though we do not use "jest-electron", the recommend using macOS (or engage in more extensive configuration
        # for Linux) in their README: https://github.com/hustcc/jest-electron/blob/b58874/README.md#ci. We've elected
        # to use Windows since macOS bills at 10x / min on GitHub actions while Windows is 2x / min.
        runs-on: windows-latest

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 14
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14

            - name: Run `yarn -i` in /desktop
              working-directory: client-applications/desktop
              run: yarn -i

            - name: Run `yarn test` in /desktop
              working-directory: client-applications/desktop
              run: |
                  echo @'
                  ==============================
                  Jest may report:

                    > The following files share their name; please adjust your hasteImpl:
                    >   * <rootDir>/app/package.json
                    >   * <rootDir>/package.json"

                  This warning can likely be ignored based on:
                    1. The test suites execute fine with it.
                    2. This GitHub issue stating it's a no-op outside of Facebook https://github.com/facebook/jest/issues/8114
                  ==============================
                  '@
                  yarn test-ci

    # Building
    # Check that the Client Applications build.
    client-applications-check-pr-building:
        name: Building on ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}

        strategy:
            matrix:
                config:
                    - name: Windows
                      os: windows-2016
                    - name: macOS
                      os: macos-10.14

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            # To retrieve Fractal protocol libraries from AWS S3
            - name: Configure AWS S3 CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Set Deploy Environment Based on Git Branch
              shell: bash
              run: |
                  if [ "${GITHUB_REF##*/}" == "master" ]; then
                      echo "DEPLOY_ENVIRONMENT=prod" >> $GITHUB_ENV
                  elif [ "${GITHUB_REF##*/}" == "staging" ]; then
                      echo "DEPLOY_ENVIRONMENT=staging" >> $GITHUB_ENV
                  else
                      echo "DEPLOY_ENVIRONMENT=dev" >> $GITHUB_ENV
                  fi
                  echo "deploy_environment is set to: $DEPLOY_ENVIRONMENT"

            ############################# Windows Configuration Steps START #############################

            - name: Install cmake via Chocolatey on Windows GHA Machine
              if: runner.os == 'Windows'
              uses: crazy-max/ghaction-chocolatey@v1
              with:
                  args: install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

            - name: Set up Visual Studio Developer Command Prompt (for nmake)
              if: runner.os == 'Windows'
              uses: ilammy/msvc-dev-cmd@v1

            ############################# Windows Configuration Steps END #############################

            ############################# Unix Configuration Steps START #############################

            - name: Install macOS Codesigning Certificates on macOS GHA Machine
              if: runner.os == 'macOS'
              uses: apple-actions/import-codesign-certs@v1
              with:
                  p12-file-base64: ${{ secrets.MACOS_SIGNING_CERTIFICATE }}
                  p12-password: ${{ secrets.MACOS_SIGNING_CERTIFICATE_PASSWORD }}

            - name: Install Linux Client Protocol Dependencies on Linux Ubuntu GHA Machines
              if: runner.os == 'Linux'
              working-directory: protocol
              run: ./setup-linux-build-environment.sh

            ############################# Unix Configuration Steps END #############################

            - name: Build the Windows Electron Application
              if: runner.os == 'Windows'
              shell: cmd # Acts as Visual Studio Developer Command Prompt due to ilammy/msvc-dev-cmd@v1
              working-directory: client-applications\desktop
              run: .\publish.bat -version=1.0.0 -bucket=not-applicable -env=${{ env.DEPLOY_ENVIRONMENT }} -publish=false

            - name: Build the macOS Electron Application
              if: runner.os == 'macOS'
              env:
                  FRACTAL_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk" # Necessary for building on macOS (protocol does NOT support 10.15+ SDKs)
              working-directory: client-applications/desktop
              run: |
                  # Explicitly retrieve macOS 10.14 SDK
                  wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.14.sdk.tar.xz

                  # Untar it
                  xz -d MacOSX10.14.sdk.tar.xz
                  tar -xf MacOSX10.14.sdk.tar

                  # Move it to the right folder for building the protocol
                  mv MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

                  # Build the Fractal protocol and package the Electron application
                  ./publish.sh --version 1.0.0 --bucket not-applicable --env ${{ env.DEPLOY_ENVIRONMENT }} --publish false
