# workflows/core-ts-linting.yml
#
# Core TypeScript Library: Check PR
# Checks a Core-TS PR for linting and testing success.

name: "Core TypeScript Library: Check PR"

on:
  push:
    # Trigger runs on our default branch, `dev`, to upload code coverage reports to Codecov
    branches:
      - dev
    paths:
      - "frontend/core-ts/**"
      - "!frontend/core-ts/README.md"
      - ".github/workflows/core-ts-check-pr.yml"
  pull_request:
    paths:
      - "frontend/core-ts/**"
      - "!frontend/core-ts/README.md"
      - ".github/workflows/core-ts-check-pr.yml"
  workflow_dispatch:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Run yarn install
        working-directory: frontend/core-ts
        run: yarn install

      - name: Check if Code Follows ESLint Standards
        working-directory: frontend/core-ts
        run: yarn run lint:check

  test:
    name: Testing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Build Monorepo Configuration
        id: config
        uses: ./.github/actions/monorepo-config
        with:
          secrets: ${{ toJSON(secrets) }}
          os: linux
          deploy: dev

      - name: Install Node.js 16
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Run yarn install
        working-directory: frontend/core-ts
        run: yarn install

      - name: Run core-ts test suite
        working-directory: frontend/core-ts
        env:
          CONFIG: ${{ steps.config.outputs.config }}
        run: yarn run test:ci

      - name: Upload Codecov Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: frontend/core-ts/coverage/clover.xml
          flags: frontend-core-ts
          fail_ci_if_error: true # optional (default = false)
