# workflows/core-ts-linting.yml
#
# Core TypeScript Library: Check PR
# Checks a Core-TS PR for linting and testing success.

name: "Core TypeScript Library: Check PR"

on:
  push:
    # Trigger runs on our default branch, `dev`, to upload code coverage reports to Codecov
    branches:
      - dev
    paths:
      - "frontend/core-ts/**"
      - "!frontend/core-ts/README.md"
      - ".github/workflows/core-ts-check-pr.yml"
  pull_request:
    paths:
      - "frontend/core-ts/**"
      - "!frontend/core-ts/README.md"
      - ".github/workflows/core-ts-check-pr.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: core-ts-check-pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"

      - name: Run yarn install
        working-directory: frontend/core-ts
        run: yarn install

      - name: Check if Code Follows ESLint Standards
        working-directory: frontend/core-ts
        run: yarn run lint:check

  test:
    name: Testing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"

      - name: Run yarn install
        working-directory: frontend/core-ts
        run: yarn install

      - name: Run core-ts test suite
        working-directory: frontend/core-ts
        run: yarn run test:ci

      - name: Upload Codecov Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: frontend/core-ts/coverage/clover.xml
          flags: frontend-core-ts
          fail_ci_if_error: true # optional (default = false)
