# workflows/host-service-check-pr.yml
#
# Host Service: Check PR
# Checks an Host Service PR for linting and building success.

name: "Host Service: Check PR"

on:
  push:
    # Trigger Host Service CI to run when commits that modify Host Service source files
    # are pushed to `dev`, since we need to run Host Service CI in order to generate an
    # updated test coverage report for the `dev` branch.
    branches:
      - dev
    paths:
      - "host-service/**"
      - "!host-service/README.md"
      - "webserver/db_migration/schema.sql"
      - ".github/workflows/host-service-check-pr.yml"
  pull_request:
    paths:
      - "host-service/**"
      - "!host-service/README.md"
      - "webserver/db_migration/schema.sql"
      - ".github/workflows/host-service-check-pr.yml"
  workflow_dispatch:

jobs:
  # Building
  # Check that the Host Service builds.
  host-service-check-pr-building:
    name: Building
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          # Get the whole git history. We must do this because the
          # Codecov requires the full history to upload coverage reports
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16"

      - name: Authenticate Go commands with GitHub
        env:
          GH_USERNAME: ${{ secrets.GHA_USERNAME }}
          GH_PAT: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
        run: git config --global url.https://$GH_USERNAME:$GH_PAT@github.com/.insteadOf https://github.com/

      # Check go project (clean, build, vet, format, lint, test, docs)
      - name: Check Go project
        working-directory: host-service
        env:
          HEROKU_USER: ${{ secrets.HEROKU_DEVELOPER_LOGIN_EMAIL }}
          HEROKU_APIKEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Add Go to path
          PATH=$PATH:~/go/bin

          # This checks for building, vet, format and lint, and will fail if unformatted
          make check

          # Show format-induced diff in GitHub Actions logs
          printf "\n\n\n==============\n"
          git diff HEAD --
          printf "\n==============\n\n\n"

          # This will return an error if there is a non-empty diff
          git diff-index --quiet HEAD --
