# workflows/log-analysis-analyze-datadog-events.yml
#
# Log Analysis: Analyze Datadog Events
# Runs daily, running analysis on the Datadog events from the past week.

name: "Log Analysis: Analyze Datadog Events"

on:
  schedule:
    - cron: "* 13 * * *" # every day at 1

jobs:
  log-analysis-analyze-datadog-events-main:
    name: Run Events Analysis
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Git repository
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dotenv, numpy, and datadog, boto3
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv numpy datadog boto3

      - name: Run Webserver Events Analysis Python Script
        run: python log-analysis/webserver/datadog/analyze.py

      - name: Notify Slack
        run: |
          curl -X POST \
          --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"Main Webserver Weekly Events Analysis performed and visualized in Datadog.\", \"icon_emoji\": \":fractal:\"}" \
          https://hooks.slack.com/services/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
