# workflows/main-webserver-clear-logs-buckets.yml
#
# Main Webserver: Clear Webserver-Generated Logs S3 Buckets
# Runs monthly, emptying the S3 buckets which stores the protocol logs and AWS SSM logs.

name: "Main Webserver: Clear Webserver-Generated Logs S3 Buckets"

on:
    schedule:
        - cron: "0 0 1 * *" # every month

jobs:
    main-webserver-clear-protocol-logs:
        name: Empty Protocol Logs from S3 Bucket
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

            - name: Empty S3 Bucket
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: fractal-protocol-logs
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  AWS_REGION: "us-east-1"

    main-webserver-clear-container-outputs:
        name: Empty Container Outputs from S3 Bucket
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                  fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

            - name: Empty S3 Bucket
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: fractal-container-outputs
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  AWS_REGION: "us-east-2"

    notify-slack:
        name: Notify Slack
        needs:
            [
                main-webserver-clear-container-outputs,
                main-webserver-clear-protocol-logs,
            ]
        if: success()
        runs-on: ubuntu-20.04
        steps:
            - name: Notify Slack
              run: |
                  curl -X POST \
                  --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"Fractal Bot\", \"text\": \"Monthly fractal-container-outputs and fractal-protocol-logs S3 Buckets Clearing Performed.\", \"icon_emoji\": \":fractal:\"}" \
                  ${{ secrets.SLACK_HOOKS_ENDPOINT }}
