# workflows/markdown-linting.yml
#
# Markdown: Linting
# Lint Markdown files using Prettier.

name: "Markdown: Linting"

on:
  pull_request:
    paths:
      - "**.md"
      - "**/**.md"
      - ".github/**/**.md"
      - ".github/workflows/markdown-linting.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: markdown-linting-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  markdown-linting-main:
    name: Lint Markdown Files
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Node.js 16
        uses: actions/setup-node@v3.1.0
        with:
          node-version: "16"

      # We have to use npm install -g here, as the yarn
      # equivalent "yarn global add" doesn't correctly
      # add the command to the path in GitHub Actions.
      - name: Install Prettier
        run: npm install -g prettier

      - name: Check if Markdown files are Formatted
        run: prettier --check '**/**.md' # Prettier glob syntax hits all .md files with this
