# workflows/meta-label-pull-requests.yml
#
# Meta: Label Pull Requests
# Labels pull requests with the subprojects they touch.

name: "Meta: Label Pull Requests"

on: pull_request

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: meta-label-pull-requests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  meta-label-pull-requests-main:
    name: Label Pull Request
    runs-on: ubuntu-20.04

    env:
      PR_LABEL_PREFIX: "üìÅ Repo: "

    steps:
      - name: Label Pull Request (.github, backend, and browser subprojects)
        uses: adamzolyak/monorepo-pr-labeler-action@4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: ".github|backend|browser"
        with:
          prefix: ${{ env.PR_LABEL_PREFIX }}

      - name: Label Pull Request (monorepo root)
        uses: adamzolyak/monorepo-pr-labeler-action@4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: ${{ env.PR_LABEL_PREFIX }}
