# workflows/shell-scripts-linting.yml
#
# Shell Scripts: Linting
# Lint and enforce good practices for shell scripts.

name: "Shell Scripts: Linting"

on:
  pull_request:
    paths:
      - "**/*.sh"
      - ".github/workflows/shell-scripts-linting.yml"
  workflow_dispatch:

jobs:
  shell-scripts-linting-main:
    name: Lint Shell Scripts
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"

      - name: Install beautysh
        working-directory: mandelbox-images/helper_scripts
        run: pip install -r requirements.txt

      - name: Run Beautysh to Check Scripts Formatting
        run: beautysh **/*.sh --indent-size 2 --check

      - name: Check that All Bash Scripts Start with "#!/bin/bash"
        run: .github/workflows/helpers/shell-scripts/check-shebang.sh

      - name: Check that All Bash Scripts Contain "set -Eeuo pipefail"
        run: .github/workflows/helpers/shell-scripts/check-pipefail.sh
