# workflows/webserver-trigger-heroku-ci-and-upload-codecov-report.yml
#
# Webserver: Trigger Heroku CI & Upload Codecov Report
# Manually trigger Heroku CI via the Heroku Platform API rather than using
# heroku ci:run. When we use heroku ci:run to trigger a test run on Heroku, we
# have to wait for the test run to finish before our job is complete. By
# triggering the test run manually via the Platform API, we can return from our
# workflow immediately after creating the test run.

name: "Webserver: Trigger Heroku CI & Upload Codecov Report"

on:
  push:
    # Trigger Heroku CI to run when commits that modify Webserver source files
    # are pushed to `dev`, since we need to run Heroku CI in order to generate an
    # updated test coverage report for the `dev` branch.
    branches:
      - dev
    paths:
      - "webserver/**.py"
      - ".github/workflows/webserver-trigger-heroku-ci-and-upload-codecov-report.yml"
  pull_request:
    paths:
      - "webserver/**.py"
      - ".github/workflows/webserver-trigger-heroku-ci-and-upload-codecov-report.yml"
  workflow_dispatch:

jobs:
  webserver-trigger-heroku-ci:
    name: Trigger Test Run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }} # must checkout the branch, not just the commit, for Heroku CI to work

      - name: Run and Wait for Heroku CI Test Run
        working-directory: webserver
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
        run: |
          heroku --version
          heroku ci:run --pipeline ${{ secrets.HEROKU_PIPELINE_NAME }}
