# workflows/webserver-trigger-heroku-ci-and-upload-codecov-report.yml
#
# Webserver: Trigger Heroku CI & Upload Codecov Report
# Manually trigger Heroku CI via the Heroku Platform API rather than using
# heroku ci:run. When we use heroku ci:run to trigger a test run on Heroku, we
# have to wait for the test run to finish before our job is complete. By
# triggering the test run manually via the Platform API, we can return from our
# workflow immediately after creating the test run.

name: "Webserver: Trigger Heroku CI & Upload Codecov Report"

on:
  push:
    # Trigger runs on our default branch, `dev`, to upload code coverage reports to Codecov
    branches:
      - dev
    paths:
      - "backend/webserver/**.py"
      - "backend/webserver/tests"
      - ".github/workflows/webserver-trigger-heroku-ci-and-upload-codecov-report.yml"
  pull_request:
    paths:
      - "backend/webserver/**.py"
      - "backend/webserver/tests"
      - ".github/workflows/webserver-trigger-heroku-ci-and-upload-codecov-report.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  webserver-trigger-heroku-ci:
    name: Trigger Test Run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }} # must checkout the branch, not just the commit, for Heroku CI to work

      - name: Run and Wait for Heroku CI Test Run
        working-directory: backend/webserver
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEVELOPER_API_KEY }}
        run: |
          heroku --version
          heroku ci:run --pipeline whist-server
