# workflows/workflows-linting.yml
#
# Workflows: Linting
# Lint YAML workflows using Prettier.

name: "Workflows: Linting"

on:
    pull_request:
        branches:
            - master
            - staging
            - dev
        paths:
            - ".github/workflows/**"
            - "!.github/workflows/README.md"
            - ".github/workflows/workflows-linting.yml"
    workflow_dispatch:

jobs:
    workflows-linting-main:
        name: Lint Github Actions Workflows
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Install Node.js 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install Prettier
              run: npm install -g prettier

            - name: Check if Code is Formatted
              working-directory: .github/workflows
              run: prettier --check '*.yml'
